###################### Filebeat Configuration - WAF Logs ########################

# ================================== Template ==================================
setup.template.enabled: true
setup.template.name: "caddy-waf"
setup.template.pattern: "caddy-waf-*"
setup.template.overwrite: true
setup.template.type: "composable"
setup.ilm.enabled: true
setup.ilm.check_exists: true
setup.ilm.overwrite: true

filebeat.inputs:
  - type: filestream
    id: waf-threats
    enabled: true
    paths:
      - /var/log/caddy/waf_wan.log
      - /var/log/caddy/waf_lan.log
    parsers:
      - ndjson:
          target: ""
    fields:
      log_type: "waf_threat"
    fields_under_root: true

  - type: filestream
    id: blocked-ips
    enabled: true
    paths:
      - /var/log/caddy/blocked_ip_events.log
    parsers:
      - ndjson:
          target: ""
    fields:
      log_type: "blocked_ip_event"
    fields_under_root: true

# ================================== Output ===================================
output.elasticsearch:
  hosts: ["https://10.246.50.82:9200"]
  username: "elastic"
  password: "KWZNH8hg3GQ64Sf"
  ssl:
    enabled: true
    verification_mode: none

  # Data Stream routing based on log_type
  indices:
    - index: "caddy-waf-waf-threats"
      when.equals:
        log_type: "waf_threat"
    - index: "caddy-waf-blocked-ips"
      when.equals:
        log_type: "blocked_ip_event"

# ================================== Logging ==================================
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
