###########################
# Filebeat for Caddy + WAF
###########################

# Filebeat data and log paths
path.data: /var/lib/filebeat
path.logs: /var/log/filebeat

# ================================
# INPUT: Caddy + WAF JSON logs
# ================================
filebeat.inputs:
  - type: filestream
    id: caddy-waf-input
    enabled: true

    # Paths to Caddy and WAF logs
    paths:
      - /var/log/caddy/waf_*.log
      - /var/log/caddy/access_*.log

    # Native JSON parsing
    json.keys_under_root: true
    json.add_error_key: true

    # Custom fields for the SIEM
    fields:
      app: caddy-waf
      environment: production
    fields_under_root: true

    # Reading optimizations
    ignore_older: 24h        # ignore logs older than 24 hours
    scan_frequency: 10s      # check for new files every 10 seconds
    close_inactive: 5m       # close inactive files after 5 minutes

# ================================
# FILEBEAT MODULES (disabled)
# ================================
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

# ================================
# TEMPLATE and ILM (index management)
# ================================
setup.template.enabled: true
setup.template.name: "caddy-waf"
setup.template.pattern: "caddy-waf-*"
setup.ilm.enabled: false
# setup.ilm.rollover_alias: "caddy-waf"
# setup.ilm.pattern: "{now/d}-000001"

# ================================
# OUTPUT: Direct Elasticsearch
# ================================
output.elasticsearch:
  hosts: ["https://10.246.50.82:15601"]
  username: "elastic"        # set your real username if needed
  password: "changeme"       # set your real password if needed
  ssl.verification_mode: none  # accept self-signed certificates
  index: "caddy-waf-%{+yyyy.MM.dd}"
  worker: 2
  bulk_max_size: 4096
  compression_level: 3

# ================================
# PROCESSORS
# ================================
processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_process_metadata: ~
  - timestamp:
      field: "@timestamp"
      layouts:
        - ISO8601

# ================================
# LOCAL FILEBEAT LOGGING
# ================================
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644