###################### Filebeat Configuration - WAF Logs ########################

filebeat.inputs:
  - type: filestream
    id: waf-threats
    enabled: true
    paths:
      - /var/log/caddy/waf_wan.log
      - /var/log/caddy/waf_lan.log
    encoding: utf-8
    json.keys_under_root: true
    json.overwrite_keys: true
    fields:
      log_type: waf_threat
    processors:
      - drop_fields:
          fields: ["message"]

  - type: filestream
    id: blocked-ips
    enabled: true
    paths:
      - /var/log/caddy/blocked_ip_events.log
    encoding: utf-8
    json.keys_under_root: true
    json.overwrite_keys: true
    fields:
      log_type: blocked_ip
    processors:
      - drop_fields:
          fields: ["message"]

# ================================== Output ===================================
output.elasticsearch:
  hosts: ["https://10.246.50.82:9200"]
  username: "elastic"
  password: "KWZNH8hg3GQ64Sf"
  ssl:
    enabled: true
    verification_mode: none
  index: "waf-%{+yyyy.MM.dd}"

setup.template.enabled: false

# ================================== Logging ==================================
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat