setup.template.enabled: true
setup.template.name: caddy-waf
setup.template.pattern: caddy-waf-*
setup.ilm.enabled: true

filebeat.inputs:
  - type: filestream
    enabled: true
    paths:
      - /var/log/caddy/waf_wan.log
      - /var/log/caddy/waf_lan.log
      - /var/log/caddy/blocked_ip_events.log
    parsers:
      - ndjson:

output.elasticsearch:
  hosts: ["https://10.246.50.82:9200"]
  username: "elastic"
  password: "KWZNH8hg3GQ64Sf"
  ssl.verification_mode: none

logging.level: info
